import Nav from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: {
  children: React.ReactNode
  teams: React.ReactNode

}) { 
  return (
    <html lang="en">
       
      <body className={inter.className}>
      <div className='grid grid-cols-1 auto-rows-fr'>
        <div>
        {props.teams}
       
        </div>
        <div className='h-screen'>
        {props.children}
       
        </div>
      </div>
        </body>
    </html>
  )
}
