import Nav from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bootcamp Roshka',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
 
}) {
  return (
    <html lang="en">
       
      <body className={inter.className}>
      <div className='supermain'>
        <div>
        <Nav/>
       
        </div>
        <div className='h-screen'>
        {children}
       
        </div>
      </div>
        </body>
    </html>
  )
}
